extends Node
## S3 (docs/refactor/SYSTEMS.MD): sweeps every level in Data through S2's
## LevelSimulator under three baseline strategies and writes docs/BALANCE.md as a
## level x strategy x result table. "Nedelej zavery, jen data" — reports only, no
## judgment calls about whether any of this is good or bad balance.
##
## Manual, not part of verify.sh's gate — like _perf_horde.gd -> docs/PERF.md, this
## plays every level to completion three times each, and per-run wall-clock cost has
## been observed (S2's PROGRESS.md entry) to vary a lot with machine load, so a full
## sweep can take a long time. Run by hand:
##   godot --headless --path . --fixed-fps 60 --main-scene res://scenes/_balance_sweep.tscn

const SEED := 20260829
## Below S2's own 36000-frame default: bounding worst-case sweep wall-clock time
## matters more here than giving a single stalled run the absolute maximum benefit of
## the doubt — a strategy that cannot resolve a level within 3 simulated minutes is
## itself a reportable data point ("timed_out"), not a run worth waiting out fully.
## Confirmed via a real run: levels 1 and 2 both carry a pre-existing, already-tracked
## defect (scripts/_test_levels.gd's own KNOWN_BROKEN dict — the objective cell sits
## outside the level's own 24x24 grid, docs/core/16) that makes the objective
## unreachable to AStarGrid2D regardless of what any strategy builds, so every
## strategy on those two levels genuinely CANNOT resolve and would otherwise burn the
## full budget three times over for no new information.
const MAX_FRAMES := 10800

var completed := false

## (display label, concrete SimStrategy subclass) — the three named in S3's own spec.
const STRATEGIES := [
	["build nothing", "SimStrategyPassive"],
	["build cheap towers evenly", "SimStrategyCheapEven"],
	["spam Quick Hit", "SimStrategyQuickHitSpam"],
]

func _make_strategy(class_id: String) -> SimStrategy:
	match class_id:
		"SimStrategyPassive":
			return SimStrategyPassive.new()
		"SimStrategyCheapEven":
			return SimStrategyCheapEven.new()
		"SimStrategyQuickHitSpam":
			return SimStrategyQuickHitSpam.new()
	return null

func _outcome_label(r: Dictionary) -> String:
	if r.get("timed_out", false):
		return "TIMEOUT"
	return "WIN" if r.get("victory", false) else "LOSS"

func _ready() -> void:
	var wd := Timer.new()
	wd.wait_time = 1800.0
	wd.one_shot = true
	add_child(wd)
	wd.timeout.connect(func():
		if not completed:
			print("FAILED: watchdog fired")
			get_tree().quit(1))
	wd.start()
	call_deferred("_run")

func _run() -> void:
	var rows: Array[String] = []
	rows.append("# Balance sweep — S2 x S3 (docs/refactor/SYSTEMS.MD)")
	rows.append("")
	rows.append("Generated by scripts/_balance_sweep.gd via S2's LevelSimulator. Every cell is the")
	rows.append("SAME seed (%d), so a column-to-column comparison at a fixed level is fair; do NOT" % SEED)
	rows.append("compare seeds against each other since none are varied here. Data only, no")
	rows.append("conclusions drawn — per S3's own \"Nedelej zavery, jen data.\"")
	rows.append("")
	rows.append("`wave` is the wave index reached (0-based) at the time the run ended, win, loss,")
	rows.append("or TIMEOUT (the run did not resolve within %d simulated frames / %.0f simulated" %
		[MAX_FRAMES, MAX_FRAMES / 60.0])
	rows.append("seconds — itself a reportable result, not a harness failure).")
	rows.append("")
	rows.append("Levels 1 and 2 show TIMEOUT under every strategy for the same reason, unrelated")
	rows.append("to any strategy's decisions: both carry a pre-existing, already-tracked defect")
	rows.append("(scripts/_test_levels.gd's own `KNOWN_BROKEN` dict — the objective cell sits")
	rows.append("outside the level's own 24x24 grid, see docs/core/16) that makes the objective")
	rows.append("unreachable to pathfinding regardless of what gets built.")
	rows.append("")
	rows.append("| level | strategy | result | focus | max_focus | tolerance | dopamine | kills | wave |")
	rows.append("|---|---|---|---|---|---|---|---|---|")

	for i in range(Data.get_level_count()):
		var lv := Data.get_level(i)
		for entry in STRATEGIES:
			var label: String = entry[0]
			var strategy := _make_strategy(entry[1])
			print("-- level %d (%s) / %s --" % [lv.id, lv.display_name, label])
			var sim := LevelSimulator.new()
			add_child(sim)
			var r: Dictionary = await sim.run(lv.id, SEED, strategy, MAX_FRAMES)
			sim.queue_free()
			await get_tree().process_frame
			print("   %s" % r)
			rows.append("| %s (id %d) | %s | %s | %d | %d | %.1f | %d | %d | %d |" % [
				lv.display_name, lv.id, label, _outcome_label(r),
				r.get("focus", -1), r.get("max_focus", -1), r.get("tolerance", -1.0),
				r.get("dopamine", -1), r.get("kills", -1), r.get("wave", -1)])

	var f := FileAccess.open("res://docs/BALANCE.md", FileAccess.WRITE)
	f.store_string("\n".join(rows) + "\n")
	f.close()

	completed = true
	print("\nwrote docs/BALANCE.md")
	get_tree().quit(0)
